### ISSUE TITLE
export component sans aet

### ISSUE THREAD

**Issue by TagZK** [salimkanoun/Orthanc-Tools-JS#544]
SendAetDropdown.js:70 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at SendAetDropdown.render (SendAetDropdown.js:70)
    at finishClassComponent (react-dom.development.js:17485)
    at updateClassComponent (react-dom.development.js:17435)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at batchedEventUpdates$1 (react-dom.development.js:22403)
    at batchedEventUpdates (react-dom.development.js:3745)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
    at attemptToDispatchEvent (react-dom.development.js:6005)
    at dispatchEvent (react-dom.development.js:5924)
    at unstable_runWithPriority (scheduler.development.js:646)
    at dispatchUserBlockingUpdate (react-dom.development.js:5894)
SendAetDropdown.render @ SendAetDropdown.js:70
finishClassComponent @ react-dom.development.js:17485
updateClassComponent @ react-dom.development.js:17435
beginWork @ react-dom.development.js:19073
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedEventUpdates$1 @ react-dom.development.js:22403
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
dispatchUserBlockingUpdate @ react-dom.development.js:5894
index.js:1 The above error occurred in the <SendAetDropdown> component:

    at SendAetDropdown (http://localhost:3000/static/js/main.chunk.js:24506:5)
    at div
    at div
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:134531:22
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:134476:23
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:189734:30)
    at http://localhost:3000/static/js/vendors~main.chunk.js:131537:24
    at http://localhost:3000/static/js/vendors~main.chunk.js:170131:20
    at Overlay (http://localhost:3000/static/js/vendors~main.chunk.js:134033:22)
    at ExportTool (http://localhost:3000/static/js/main.chunk.js:26826:5)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:171329:75)
    at div
    at div
    at ToolsPanel (http://localhost:3000/static/js/main.chunk.js:27919:5)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:171329:75)
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:189734:30)
    at http://localhost:3000/static/js/vendors~main.chunk.js:130804:22
    at http://localhost:3000/static/js/vendors~main.chunk.js:133879:23
    at nav
    at http://localhost:3000/static/js/vendors~main.chunk.js:133750:96
    at div
    at NavBar (http://localhost:3000/static/js/main.chunk.js:27475:5)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:174022:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:173642:35)
    at App (http://localhost:3000/static/js/main.chunk.js:322:5)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:171329:75)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:171042:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedEventUpdates$1 @ react-dom.development.js:22403
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
dispatchUserBlockingUpdate @ react-dom.development.js:5894
react-dom.development.js:11340 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at SendAetDropdown.render (SendAetDropdown.js:70)
    at finishClassComponent (react-dom.development.js:17485)
    at updateClassComponent (react-dom.development.js:17435)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at batchedEventUpdates$1 (react-dom.development.js:22403)
    at batchedEventUpdates (react-dom.development.js:3745)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
    at attemptToDispatchEvent (react-dom.development.js:6005)
    at dispatchEvent (react-dom.development.js:5924)
    at unstable_runWithPriority (scheduler.development.js:646)
    at dispatchUserBlockingUpdate (react-dom.development.js:5894)

**Comment by salimkanoun** [comment]
Fixed
